// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
        int N = Integer.parseInt(args[0]);
        int greater = 0, less_equal = 0;

        for (int i = 0; i < N; i++) {
            if (Math.random() > 0.5) {
                greater++;
            } else {
                less_equal++;
            }
        }

        System.out.printf("> 0.5: %d times\n", greater);
        System.out.printf("<= 0.5: %d times\n", less_equal);
        if (less_equal != 0) {
            System.out.printf("Ratio: %.7f\n", (double) greater / less_equal);
        } else {
            System.out.println("Ratio: Undefined (division by zero)");
        }	
	}
}
